### ISSUE TITLE
Teleportal direct link is kinda annoying when every area has already been visited (real visit, not the fake itorash visit)

### ISSUE THREAD

**Issue by Hugoshido** [randovania/open-dread-rando#125]

**Comment by henriquegemignani** [comment]
What exactly is the issue here?

**Comment by duncathan** [comment]
when fixing the linked teleportal crash I also added a feature where the first time you use any teleportal, it will only go directly to its partner rather than the linked teleportal screen. this is so that if logic expects you to use a teleportal to visit a region for the first time, linking the teleportals won't prevent you from visiting. I have a fix I haven't pushed yet where this behavior only happens if the destination is an area you haven't visited
