### ISSUE TITLE
Prevent game from starting if current version is different from version used to randomize

### ISSUE THREAD

**Issue by henriquegemignani** [randovania/open-dread-rando#35]
This would be focused entirely on romfs.

1.0.0, 1.0.2 and 1.0.3 have the same romfs. 1.0.1 has some modified romfs, but that version is not interesting anyway.
2.0.0 has a modified romfs with significant changes.

Playing 2.0.0 with a romfs that comes from 1.0.X have at least missing text, but it's unknown if subtle things break.

**Comment by duncathan** [comment]
some things worth noting:
 - 2.0.0 romfs is backwards-compatible with 1.0.0 for randomization purposes
 - 1.0.0 romfs is missing a couple of new scripts in the system pkg as well as a few new strings in the localization files, but playing on normal or hard mode in 2.0.0 with a 1.0.0 romfs should have no gameplay effects

dark suggested patching an unused/stubbed Lua function to return a different value in each exefs in order to verify the game version is what's expected. whether we prevent the game from starting entirely is up for some discussion still but it's worthwhile to get a game version check implemented at some point

**Comment by duncathan** [comment]
I'm gonna consider this addressed by #99

**Comment by henriquegemignani** [comment]
We don't detect/prevent the user from playing on 2.0+ but providing a 1.0 dump to Randovania.

But I'm not sure how critical is that.

**Comment by duncathan** [comment]
I'm not particularly concerned about it. Detecting unsupported versions was the important part imo
