### ISSUE TITLE
Reloading Checkpoint sets Samus to a different Spawn Point

### ISSUE THREAD

**Issue by dyceron** [randovania/open-dread-rando#58]
Arriving in the following elevators/teleportals and then reloading from checkpoint sets Samus' spawn to a different room. Also sets the save point of the file to that new room. Seems to only happen on the first visit to an area.

Some rooms could be missing, so this might need more testing.

### Burenia
- Elevator to Ghavoran -> Upper Shuttle to Dairon
- Elevator to Artaria -> Upper Shuttle to Dairon

### Cataris
- Blue Teleportal to Artaria -> Elevator to Artaria
- Shuttle to Cataris -> Elevator to Artaria

### Darion
- Elevator to Artaria -> Shuttle to Cataris
- East Elevator to Ferenia -> Shuttle to Cataris

### Ferenia
- Cyan Teleportal to Burenia -> East Elevator to Dairon

### Ghavoran
- Orange Teleportal to Cataris -> Elevator to Burenia

**Comment by dyceron** [comment]
Seems like using any teleportal, transport, or shuttle sets the Save File to that room. Needs to be tested for all of these rooms though.

**Comment by TheyCallMeXander** [comment]
I had an interesting situation where I entered Cataris via the Red Teleportal, and left the game. When I entered back into the save file it placed me at Artaria> Cataris elevator. I would like to mention I had never previously entered this room or used the elevator from either side.

**Comment by ScorelessPine** [comment]
Attached are two log files using the Debug Logger mod you posted on Discord. The file names should well enough describe what I did during each log but I'll describe them here as well.
This first one, I started a new game which placed me at Dairon's Yellow TP, I took the teleportal and once on the other side, immediately loaded my save. This led to a crash.
[Ryujinx Start game - teleport - reload save crash.log](https://github.com/randovania/open-dread-rando/files/8238713/Ryujinx.Start.game.-.teleport.-.reload.save.crash.log)
This second one, I performed the same steps except I did not reload the save, I just copied the log file while the emulator was still running, so it gives a little bit better of an idea when the save file might have been created.
[Ryujinx Start game - teleport.log](https://github.com/randovania/open-dread-rando/files/8238711/Ruijinx.Start.game.-.teleport.log)

These logs don't technically perfectly describe the above issue, however I'm certain that the cause is the same. In the above case, the game creates a save at the default scenario location after entering an area for the first time, and in this case, it creates a save in the same way, but the location is glitched for some reason, causing a crash upon loading the save file from that point onward.
