### ISSUE TITLE
Bypassing Ataris (non-broken) E.M.M.I. cutscene can result in losing items

### ISSUE THREAD

**Issue by xmeehan** [randovania/open-dread-rando#64]
I was playing a seed and mostly just messing around to see things that happened and found a scenario where I bypassed the white E.M.M.I. cutscene but was able to destroy the Central Unit but at some point lost Varia Suit which I had picked up beforehand. (To be clear, this is different than the visual suit glitch where Progressive Suit doesn't visually change after picking it up; I was taking damage in hot rooms and the status screen displayed Power Suit.) This is definitely an edge case but wanted to make sure it was known.

Full details: I found Spider Magnet before Broken E.M.M.I., followed by Phantom Cloak in the first E.M.M.I. zone room. Instead of going into the room with the cutscene for the white E.M.M.I. I instead went and found Varia on Corpius. I found Progressive Charge right outside so I decided to go straight to the Central Unit. Since I hadn't triggered the E.M.M.I. cutscene it didn't seem to be wandering the zone and in the Central Unit room the door didn't close and the circles/lasers didn't fire. When I destroyed the Central Unit the Omega Blaster cutscene didn't trigger. At this point I went back and triggered the cutscene I bypassed initially but since the thermal door was open I went back to the Central Unit instead of leaving the E.M.M.I. zone as I would normally. The circles and lasers still didn't fire but the Central Unit was floating again and the door closed. After destroying the Central Unit the Omega Blaster cutscene triggered as normal but leaving the room the alarms weren't raised and I realized the E.M.M.I. zone doors were open. I decided to see what I could do with the Omega Blaster outside of the E.M.M.I. zone out of curiosity and I noticed that in a hot room I was taking damage and checking Samus's status screen only showed the Power Suit equipped. I went back into the E.M.M.I. zone and the doors locked and I was able to destroy the E.M.M.I. (who was frozen in place) but I was still left with only the Power Suit.

**Comment by xmeehan** [comment]
Attaching .rdvgame file
[2022-03-05-19-49-19_Dread_Kraid Nailong Scourge.rdvgame.txt](https://github.com/randovania/open-dread-rando/files/8192083/2022-03-05-19-49-19_Dread_Kraid.Nailong.Scourge.rdvgame.txt)

**Comment by Unknownforce351** [comment]
Two things:
1.) If you loaded to a checkpoint before saving after killing Corpius, then this is a known bug of progressive items being on Corpius.
2.) The behavior of the broken CU room (no threat) and emmi frozen and all that, is also known and has two possible triggers:
  a.) Not running through the very first emmi chase (where it locks the emmi doors and forces you to slide into the water and wait till it unlocks them)
  b.) Entering the CU room from the bottom open door instead of the top slide in.

Im guessing that it was just coincidence that you managed to trigger both of the above cases in the same run.
